$st="dell" #keyword searc
$sg=""
$c="" #categories
$s="" #location 43 austin
$lp="0"
$hp="999999"
$sbn="false"
$spo="false"
$snpo="false"
$socs="false"
$sd="false"
$sca="false"
$caed="10/5/2020"
$cadb="7"
$scs="false"
$sis="false"
$col="1"
$p="1"
$ps="40"
$desc="false"
$ss="0"
$UseBuyerPrefs="true"



$url="https://www.shopgoodwill.com/Listings?"
$url+="st=$st&"
$url+="sg=$sg&"
$url+="c=$c&"
$url+="s=$s&"
$url+="lp=$lp&"
$url+="hp=$hp&"
$url+="sbn=$sbn&"
$url+="spo=$spo&"
$url+="snpo=$snpo&"
$url+="socs=$socs&"
$url+="sd=$sd&"
$url+="sca=$sca&"
$url+="caed=$caed&"
$url+="cadb=$cadb&"
$url+="scs=$scs&"
$url+="sis=$sis&"
$url+="col=$col&"
$url+="p=$p&"
$url+="ps=$ps&"
$url+="desc=$desc&"
$url+="ss=$ss&"
$url+="UseBuyerPrefs=$UseBuyerPrefs"

start-process $url