using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text;

namespace DealScanner.Repostitory.Enums.GoodWill
{
    public enum GoodWillLocation
    {
        [EnumMember(Value = "Goodwill Easter Seals of the Gulf Coast Inc.")]
        AL_Mobile = 53,
        [EnumMember(Value = "Goodwill Industries of Arkansas Inc.")]
        AR_Little_Rock = 13,
        [EnumMember(Value = "Goodwill of Central &amp; Northern Arizona")]
        AZ_Phoenix = 201,
        [EnumMember(Value = "Goodwill Industries of Southern Arizona")]
        AZ_Tucson = 148,
        [EnumMember(Value = "Goodwill South Central California")]
        CA_Bakersfield = 71,
        [EnumMember(Value = "Goodwill Industries of the Greater East Bay  Oakland Fairfield CA")]
        CA_Fairfield = 67,
        [EnumMember(Value = "Goodwill Serving the People of Southern Los Angeles County")]
        CA_Long_Beach = 57,
        [EnumMember(Value = "Goodwill Southern California")]
        CA_Los_Angeles = 78,
        [EnumMember(Value = "Goodwill Industries of Ventura and Santa Barbara Counties")]
        CA_Oxnard = 26,
        [EnumMember(Value = "Goodwill Industries Sacramento Valley")]
        CA_Sacramento = 162,
        [EnumMember(Value = "Goodwill Central Coast")] 
        CA_Salinas = 75,
        [EnumMember(Value = "Goodwill Industries of San Diego County")] 
        CA_San_Diego = 12,
        [EnumMember(Value = "Goodwill of Silicon Valley")] 
        CA_San_Jose = 119,
        [EnumMember(Value = "Goodwill of Orange County")] 
        CA_Santa_Ana = 2,
        [EnumMember(Value = "Goodwill Industries of the Redwood Empire")] 
        CA_Santa_Rosa = 120,
        [EnumMember(Value = "Goodwill Industries of San Francisco")] 
        CA_South_San_Francisco = 62,
        [EnumMember(Value = "Goodwill Industries of San Joaquin Valley Inc.")] 
        CA_Stockton = 49,
        [EnumMember(Value = "Discover Goodwill of Southern and Western Colorado")] 
        CO_Colorado_Springs = 73,
        [EnumMember(Value = "Goodwill of Western &amp; Northern CT")] 
        CT_Bridgeport = 343,
        [EnumMember(Value = "Goodwill Southern New England Inc.")] 
        CT_Hamden = 174,
        [EnumMember(Value = "Goodwill Industries of Delaware &amp; Delaware County Inc.")] 
        DE_Wilmington = 42,
        [EnumMember(Value = "Goodwill Industries of South Florida")]
        FL_Fort_Lauderdale = 16,
        [EnumMember(Value = "Goodwill Industries of SW Florida Inc.")]
        FL_Fort_Myers = 81,
        [EnumMember(Value = "Goodwill Industries of North Florida")] 
        FL_Jacksonville = 47,
        [EnumMember(Value = "Gulfstream Goodwill Industries")] 
        FL_West_Palm_Beach = 34,
        [EnumMember(Value = "Goodwill Industries of Central Florida")] 
        FL_Orlando = 109,
        [EnumMember(Value = "Goodwill Industries Big Bend Inc.")] 
        FL_Tallahassee = 176,
        [EnumMember(Value = "Goodwill-Suncoast")] 
        FL_Tampa = 66,
        [EnumMember(Value = "Goodwill Industries of the Southern Rivers")] 
        GA_Columbus = 72,
        [EnumMember(Value = "Goodwill Industries of Middle Georgia")] 
        GA_Macon = 195,
        [EnumMember(Value = " Goodwill of North Georgia")] 
        GA_Atlanta = 339,
        [EnumMember(Value = "Goodwill Southeast Georgia")] 
        GA_Savannah = 98,
        [EnumMember(Value = "Goodwill Hawaii")] 
        HI_Honolulu = 115,
        [EnumMember(Value = "Goodwill of the Heartland")] 
        IA_Iowa_City = 10,
        [EnumMember(Value = "Goodwill of Central Iowa")] 
        IA_Des_Moines = 102,
        [EnumMember(Value = "Goodwill Industries of Northeast Iowa Inc.")] 
        IA_Waterloo = 171,
        [EnumMember(Value = "Goodwill of the Great Plains Sioux City Iowa")] 
        IA_Sioux_City = 137,
        [EnumMember(Value = "Boise Metro Goodwill")] 
        ID_Boise = 159,
        [EnumMember(Value = "Goodwill Industries of Central Illinois Inc.")] 
        IL_East_Peoria = 90,
        [EnumMember(Value = "Goodwill Industries of Northern Illinois")] 
        IL_Rockford = 135,
        [EnumMember(Value = "Land of Lincoln Goodwill")] 
        IL_Springfield = 132,
        [EnumMember(Value = "Goodwill Industries of Northeast Indiana East Inc.")]
        IN_Fort_WayneEast = 340,
        [EnumMember(Value = "Goodwill Industries of Northeast Indiana Inc.")]
        IN_Fort_Wayne = 105,
        [EnumMember(Value = "Goodwill of Central &amp; Southern Indiana")] 
        IN_Indianapolis = 5,
        [EnumMember(Value = "Goodwill Industries of Michiana Inc.")] 
        IN_South_Bend = 50,
        [EnumMember(Value = "Wabash Valley Goodwill")] 
        IN_Terre_Haute = 4,
        [EnumMember(Value = "Goodwill Industries of Kansas INC.")] 
        KS_Wichita = 20,
        [EnumMember(Value = "Goodwill Industries of Kentucky")] 
        KY_Louisville = 25,
        [EnumMember(Value = "Goodwill Industries of Acadiana")] 
        LA_Lafayette = 202,
        [EnumMember(Value = "Goodwill of North Louisiana")] 
        LA_Shreveport = 7,
        [EnumMember(Value = "Goodwill Industries of the Chesapeake Inc.")] 
        MD_Baltimore = 11,
        [EnumMember(Value = "Goodwill of Greater Washington D.C.")] 
        MD_Forestville = 76,
        [EnumMember(Value = "Goodwill Monocacy Valley")] 
        MD_Frederick = 69,
        [EnumMember(Value = "Horizon Goodwill Industries")] 
        MD_Hagerstown = 184,
        [EnumMember(Value = "Goodwill of Northern New England")] 
        ME_Portland = 111,
        [EnumMember(Value = "Goodwill Industries of Southeastern MI Inc.")] 
        MI_Adrian = 55,
        [EnumMember(Value = "Goodwill Industries of Central Michigans Heartland")] 
        MI_Charlotte = 68,
        [EnumMember(Value = "Green Works")] 
        MI_Detroit = 336,
        [EnumMember(Value = "Goodwill Industries of Mid Michigan")] 
        MI_Flint = 114,
        [EnumMember(Value = "Goodwill of Greater Grand Rapids")] 
        MI_Grandville = 9,
        [EnumMember(Value = "Goodwill Industries of Southwestern Michigan")] 
        MI_Kalamazoo = 77,
        [EnumMember(Value = "Goodwill Industries of West Michigan Inc.")] 
        MI_Muskegon = 86,
        [EnumMember(Value = "Goodwill Industries of St. Clair County (Goodwill SCC)")] 
        MI_Port_Huron = 85,
        [EnumMember(Value = "Goodwill Industries of Northern Michigan Inc.")] 
        MI_Traverse_City = 89,
        [EnumMember(Value = "Goodwill-Easter Seals MN")] 
        MN_Brooklyn_Park = 106,
        [EnumMember(Value = "Goodwill of Western Missouri &amp; Eastern Kansas")] 
        MO_Blue_Springs = 58,
        [EnumMember(Value = "MERS/Missouri Goodwill Industries")] 
        MO_St_Louis = 140,
        [EnumMember(Value = "Goodwill South Mississippi")] 
        MS_Gulfport = 129,
        [EnumMember(Value = "Goodwill Industries of Mississippi")] 
        MS_Clinton = 178,
        [EnumMember(Value = "Goodwill Industries of the Southern Piedmont")] 
        NC_Charlotte = 80,
        [EnumMember(Value = "Goodwill Industries of Central North Carolina Inc.")] 
        NC_Greensboro = 46,
        [EnumMember(Value = "Goodwill Industries of Northwest North Carolina Inc.")] 
        NC_Statesville = 181,
        [EnumMember(Value = "Easter Seals Goodwill ND Inc.")] 
        ND_Bismarck = 154,
        [EnumMember(Value = "Goodwill Industries of Greater Nebraska Inc.")] 
        NE_Grand_Island = 182,
        [EnumMember(Value = "Goodwill Industries Serving Eastern Nebraska &amp; Southwest Iowa")] 
        NE_Omaha = 118,
        [EnumMember(Value = "Goodwill Industries of Southern NJ &amp; Philadelphia")] 
        NJ_Bellmawr = 136,
        [EnumMember(Value = "Goodwill Industries of Greater New York and Northern New Jersey")] 
        NY_New_York = 33,
        [EnumMember(Value = "Goodwill of Southern Nevada")] 
        NV_Las_Vegas = 147,
        [EnumMember(Value = "Goodwill Industries of Western New York")] 
        NY_Buffalo = 127,
        [EnumMember(Value = "Goodwill of The Finger Lakes")] 
        NY_Rochester = 17,
        [EnumMember(Value = "Goodwill Industries of Akron Ohio Inc.")] 
        OH_Akron = 27,
        [EnumMember(Value = "Goodwill of Ashtabula Inc.")] 
        OH_Ashtabula = 97,
        [EnumMember(Value = "Ohio Valley Goodwill Industries")] 
        OH_Cincinnati = 130,
        [EnumMember(Value = "Goodwill Industries of South Central Ohio")] 
        OH_Chillicothe = 126,
        [EnumMember(Value = "Goodwill Industries of Greater Cleveland & East Central Ohio")] 
        OH_Cleveland = 87,
        [EnumMember(Value = "Goodwill Columbus")] 
        OH_Columbus = 107,
        [EnumMember(Value = "Goodwill Easter Seals Miami Valley")] 
        OH_Dayton = 54,
        [EnumMember(Value = "Marion Goodwill Industries")] 
        OH_Delaware = 103,
        [EnumMember(Value = "Goodwill Industries of Lorain County")] 
        OH_Elyria = 172,
        [EnumMember(Value = "Licking/Knox Goodwill Industries Inc.")] 
        OH_Newark = 32,
        [EnumMember(Value = "Goodwill Industries of Northwest Ohio")] 
        OH_Oregon = 28,
        [EnumMember(Value = "Goodwill Industries of Wayne and Holmes Counties Inc.")] 
        OH_Wooster = 6,
        [EnumMember(Value = "Youngstown Area Goodwill Industries Inc.")] 
        OH_Youngstown = 84,
        [EnumMember(Value = "Zanesville Welfare Organization and Goodwill Industries Inc.")] 
        OH_Zanesville = 344,
        [EnumMember(Value = "Goodwill Industries of Southwest Oklahoma & North Texas")] 
        OK_Lawton = 188,
        [EnumMember(Value = "Goodwill Industries Ontario Great Lakes Canada")] 
        ON_London = 180,
        [EnumMember(Value = "Goodwill Industries of Lane & South Coast Counties")] 
        OR_Eugene = 59,
        [EnumMember(Value = "Goodwill Industries of the Columbia Willamette")] 
        OR_Hillsboro = 8,
        [EnumMember(Value = "Southern Oregon Goodwill Industries")] 
        OR_Medford = 15,
        [EnumMember(Value = "Goodwill Keystone Area Berwyn")] 
        PA_Berwyn = 30,
        [EnumMember(Value = "Goodwill Industries of North Central PA Inc.")] 
        PA_Falls_Creek = 146,
        [EnumMember(Value = "Goodwill Industries of North Central PA Inc.")] 
        PA_DuBois = 345,
        [EnumMember(Value = "Goodwill Industries NCPA")] 
        PA_Falls_Creek_NCPA = 341,
        [EnumMember(Value = "Goodwill Keystone Area Harrisburg")] 
        PA_Harrisburg = 199,
        [EnumMember(Value = "Goodwill of Southwestern Pennsylvania")] 
        PA_North_Versailles = 18,
        [EnumMember(Value = "Goodwill Keystone Area Reading")]
        PA_Reading = 60,
        [EnumMember(Value = "Goodwill Industries of Northeastern Pennsylvania")] 
        PA_Scranton = 179,
        [EnumMember(Value = "Goodwill Industries of Upstate/Midlands South Carolina")] 
        SC_Columbia = 193,
        [EnumMember(Value = "Goodwill Industries of Upstate/Midlands South Carolina")] 
        SC_Greenville = 22,
        [EnumMember(Value = "Palmetto Goodwill")] 
        SC_North_Charleston = 177,
        [EnumMember(Value = "Goodwill Industries of Upstate/Midlands South Carolina UNION")] 
        SC_Union = 342,
        [EnumMember(Value = "Goodwill of the Great Plains Sioux Falls  South Dakota")] 
        SD_Sioux_Falls = 163,
        [EnumMember(Value = "Goodwill Industries-Knoxville Inc.")] 
        TN_Knoxville = 337,
        [EnumMember(Value = "Chattanooga Goodwill Industries Inc.")] 
        TN_Chattanooga = 346,
        [EnumMember(Value = "Goodwill Industries of Middle Tennessee Inc.")] 
        TN_Nashville = 117,
        [EnumMember(Value = "Goodwill West Texas")] 
        TX_Abilene = 138,
        [EnumMember(Value = "Goodwill Industries of Central Texas")] 
        TX_Austin = 43,
        [EnumMember(Value = "Goodwill Industries of Southeast Texas")] 
        TX_Beaumont = 23,
        [EnumMember(Value = "Goodwill Industries of South Texas")] 
        TX_Corpus_Christi = 133,
        [EnumMember(Value = "Goodwill Industries of Central East Texas Inc.")] 
        TX_Lufkin = 74,
        [EnumMember(Value = "Shopgoodwill of El Paso")] 
        TX_El_Paso = 100,
        [EnumMember(Value = "Goodwill Industries of Fort Worth")] 
        TX_Fort_Worth = 63,
        [EnumMember(Value = "Goodwill Houston North")] 
        TX_Houston = 185,
        [EnumMember(Value = "Goodwill Industries of Northwest Texas")] 
        TX_Lubbock = 104,
        [EnumMember(Value = "Goodwill Industries of San Antonio")] 
        TX_San_Antonio = 164,
        [EnumMember(Value = "Goodwill Industries of NE Texas")] 
        TX_Sherman = 338,
        [EnumMember(Value = "Goodwill Industries of East Texas Inc.")] 
        TX_Tyler = 101,
        [EnumMember(Value = "Heart of Texas Goodwill")] 
        TX_Waco = 144,
        [EnumMember(Value = "SLC Metro Goodwill")] 
        UT_Salt_Lake_City = 192,
        [EnumMember(Value = "Rappahannock Goodwill Industries Inc.")] 
        VA_Fredericksburg = 145,
        [EnumMember(Value = "Goodwill of Central & Coastal Virginia")]
        VA_Hampton = 348,
        [EnumMember(Value = "Goodwill of Central & Coastal Virginia")]
        VA_Richmond = 200,
        [EnumMember(Value = "Goodwill Industries of the Valleys")] 
        VA_Salem = 191,
        [EnumMember(Value = "Goodwill Industries of the Columbia Inc.")] 
        WA_Pasco = 155,
        [EnumMember(Value = "Seattle Goodwill")] 
        WA_Seattle = 48,
        [EnumMember(Value = "Goodwill Industries of the Inland Northwest Curve Apparel")] 
        WA_Spokane_Curve = 198,
        [EnumMember(Value = "Goodwill Industries of the Inland Northwest")] 
        WA_Spokane = 19,
        [EnumMember(Value = "Goodwill of the Olympics and Rainier Region")] 
        WA_Tacoma = 122,
        [EnumMember(Value = "Goodwill of North Central Wisconsin")] 
        WI_Appleton = 134,
        [EnumMember(Value = "Goodwill Industries of South Central Wisconsin Inc.")] 
        WI_Madison = 108,
        [EnumMember(Value = "Goodwill Retail Services Inc.")] 
        WI_Racine = 29,
        [EnumMember(Value = "Goodwill Industries of Kanawha Valley Inc.")] 
        WV_Charleston = 56,
        [EnumMember(Value = "Goodwill Industries of KYOWVA Area Inc.")] 
        WV_Huntington = 31,
        [EnumMember(Value = "Goodwill Industries of Wyoming Inc.")] 
        WY_Cheyenne = 150,

    }
}
